import { allListings } from './data.js';

export const useCases = [
  { slug: 'ai-tools-for-training-and-development', label: 'AI Tools for Training and Development', title: 'Best AI Tools for Training and Development Teams', meta: 'Compare AI tools for training and development workflows across onboarding, compliance, enablement, and content ops.', intro: 'Use this page as a practical shortlist for training and development teams that need faster content production and cleaner rollout execution.' },
  { slug: 'sop-to-video-training', label: 'SOP to Video Training', title: 'SOP to Video Training Tools for L&D Teams', meta: 'Compare AI tools that turn SOPs into training videos for faster onboarding and compliance enablement.', intro: 'If your L&D team is buried in SOP updates, these tools help convert process docs into consistent training assets faster.' },
  { slug: 'new-hire-onboarding-automation', label: 'New Hire Onboarding Automation', title: 'AI Tools for New Hire Onboarding Automation', meta: 'Find AI tools that streamline onboarding plans, manager enablement, and day-1 readiness for employees.', intro: 'Onboarding quality often breaks when teams scale. This stack focuses on repeatable onboarding flows that reduce ramp time.' },
  { slug: 'compliance-training-content-creation', label: 'Compliance Training Content', title: 'AI Tools for Compliance Training Content Creation', meta: 'Discover AI tools to build compliance learning content, policy explainers, and mandatory training refreshers.', intro: 'Compliance teams need clear, current content. These tools help training owners produce policy-safe modules quickly.' },
  { slug: 'sales-enablement-training', label: 'Sales Enablement Training', title: 'Sales Enablement AI Tools for Internal Training', meta: 'Shortlist AI tools to create sales onboarding, objection handling drills, and coaching materials.', intro: 'Revenue teams need ongoing enablement, not one-off decks. These tools support continuous practice and reinforcement.' },
  { slug: 'customer-support-training', label: 'Customer Support Training', title: 'AI Tools for Customer Support Training Programs', meta: 'Compare AI tools for support onboarding, QA coaching, and playbook training at scale.', intro: 'Support quality depends on fast knowledge transfer. This page highlights tools that operationalize support training.' },
  { slug: 'microlearning-video-production', label: 'Microlearning Video Production', title: 'AI Tools for Microlearning Video Production', meta: 'Create short-form training videos and explainers with AI voice, avatar, and editing workflows.', intro: 'Microlearning works when production is lightweight. These tools help L&D publish frequent, focused lessons.' },
  { slug: 'manager-coaching-playbooks', label: 'Manager Coaching Playbooks', title: 'AI Tools for Manager Coaching Playbooks', meta: 'Build manager training playbooks, coaching prompts, and performance support assets with AI.', intro: 'Managers need practical coaching resources they can use in weekly 1:1s. These tools support scalable leadership development.' },
  { slug: 'knowledge-base-to-training', label: 'Knowledge Base to Training', title: 'Turn Knowledge Base Content into Training with AI', meta: 'Use AI to repurpose internal docs and wikis into learning modules, walkthroughs, and onboarding content.', intro: 'Most training content already exists in docs. This workflow helps transform static knowledge into usable learning experiences.' },
  { slug: 'product-training-rollouts', label: 'Product Training Rollouts', title: 'AI Tools for Product Training Rollouts', meta: 'Launch internal product training faster with AI-generated walkthroughs, lesson updates, and role-based content.', intro: 'When products ship quickly, training falls behind. These tools close the gap between release notes and employee readiness.' },
  { slug: 'call-review-and-coaching', label: 'Call Review and Coaching', title: 'AI Tools for Call Review and Coaching Workflows', meta: 'Identify coaching moments and build targeted training from call transcripts and conversation intelligence.', intro: 'Coaching improves when you can pinpoint patterns. These tools support data-backed call review and coaching loops.' },
  { slug: 'multilingual-employee-training', label: 'Multilingual Employee Training', title: 'AI Tools for Multilingual Employee Training', meta: 'Scale employee training globally using AI translation, voice localization, and region-specific delivery.', intro: 'Global teams need training that lands in local language and context. These tools support multilingual delivery without full rebuilds.' },
  { slug: 'ai-trainer-workflow-automation', label: 'L&D Workflow Automation', title: 'AI Workflow Automation for Training and L&D Operations', meta: 'Reduce repetitive L&D tasks with AI workflows for content creation, updates, and training operations.', intro: 'Training teams are asked to do more with less. Automation-first tools free capacity for higher-impact learning design work.' },
  { slug: 'ai-training-needs-analysis', label: 'AI Training Needs Analysis', title: 'AI Tools for Training Needs Analysis in L&D', meta: 'Assess skill gaps, role readiness, and learning priorities faster with AI-assisted training needs analysis workflows.', intro: 'When L&D planning starts with weak intake data, budgets get wasted. This page shows how to run sharper, evidence-backed needs analysis.' },
  { slug: 'ai-skills-gap-analysis-for-ld', label: 'AI Skills Gap Analysis', title: 'AI Skills Gap Analysis Tools for L&D Teams', meta: 'Use AI to map current capability vs target role proficiency and prioritize upskilling programs by business impact.', intro: 'Skills gap work is high-impact but usually manual. These tools help L&D leaders quantify priority gaps and sequence interventions.' },
  { slug: 'ai-course-outline-generator-for-subject-matter-experts', label: 'AI Course Outline Generator for SMEs', title: 'AI Course Outline Tools for Subject Matter Experts and L&D', meta: 'Turn expert interviews, SOPs, and notes into structured course outlines with objectives, modules, and assessments.', intro: 'SMEs have knowledge but not always instructional design bandwidth. AI outline workflows speed up handoff from expertise to curriculum.' },
  { slug: 'ai-policy-change-training-updates', label: 'AI Policy Change Training Updates', title: 'AI Tools for Policy Change Training Updates', meta: 'Update compliance and policy training content quickly when regulations, controls, or internal procedures change.', intro: 'Policy updates are where training debt spikes. This use case focuses on reducing time from policy change to learner-ready update.' },
  { slug: 'ai-onboarding-for-remote-teams', label: 'AI Onboarding for Remote Teams', title: 'AI Onboarding Tools for Remote and Distributed Teams', meta: 'Build consistent onboarding for distributed teams with AI-generated playbooks, async modules, and manager check-ins.', intro: 'Remote onboarding fails when context is fragmented. These tools create repeatable, manager-friendly systems for distributed ramp-up.' },
  { slug: 'ai-training-for-frontline-workers', label: 'AI Training for Frontline Workers', title: 'AI Training Tools for Frontline Worker Enablement', meta: 'Deliver clear, fast, mobile-friendly training to frontline employees across shifts, sites, and languages.', intro: 'Frontline training needs speed, clarity, and low-friction access. This page targets practical AI workflows that work in operational settings.' },
  { slug: 'ai-lms-content-migration-and-refresh', label: 'AI LMS Content Migration and Refresh', title: 'AI Tools for LMS Content Migration and Course Refresh', meta: 'Migrate legacy course libraries and refresh outdated training content with AI-assisted rewriting and media updates.', intro: 'Most LMS catalogs contain stale assets. AI can accelerate migration and modernization without rewriting every module from scratch.' },
  { slug: 'ai-train-the-trainer-programs', label: 'AI Train-the-Trainer Programs', title: 'AI Tools for Train-the-Trainer Program Design', meta: 'Create trainer certification paths, facilitation guides, and coaching assets with AI for internal academy teams.', intro: 'Scaling training quality requires stronger trainer enablement. These tools help standardize delivery while preserving facilitator flexibility.' },
  { slug: 'ai-performance-support-for-managers', label: 'AI Performance Support for Managers', title: 'AI Performance Support Tools for People Managers', meta: 'Equip managers with AI-powered coaching prompts, conversation guides, and just-in-time training support resources.', intro: 'Managers often own performance conversations without enough guidance. This use case focuses on practical, in-the-flow support tools.' },
  { slug: 'ai-compliance-audit-ready-training-records', label: 'AI Compliance Audit-Ready Training Records', title: 'AI Tools for Audit-Ready Compliance Training Records', meta: 'Maintain audit-ready training evidence with AI-assisted documentation, completion tracking, and policy linkage workflows.', intro: 'Audit pressure rises when evidence is fragmented. This workflow helps teams produce cleaner records and faster compliance responses.' },
  { slug: 'eu-ai-act-ai-literacy-training', label: 'EU AI Act AI Literacy Training', title: 'EU AI Act AI Literacy Training for Employees (Article 4)', meta: 'Shortlist AI training tools and workflows to build AI literacy programs aligned with EU AI Act Article 4 expectations.', intro: 'EU organizations now need practical AI literacy measures for staff using AI systems. This page focuses on implementation workflows, not legal guesswork.' }
];

export const roles = ['Head of L&D','L&D Manager','Training Operations Manager','Enablement Manager','HR Business Partner','People Operations Lead','Compliance Manager','Customer Support Manager','Sales Enablement Lead','Instructional Designer'].map((role) => ({
  slug: `for-${role.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  label: role,
  title: `Best AI Training Tools for ${role}`,
  meta: `Find AI tools aligned to ${role} workflows, from onboarding content to training operations and coaching support.`,
  intro: `${role}s need practical systems, not hype. This shortlist focuses on tools that improve learning delivery and team execution.`
}));

export const industries = ['Healthcare','Manufacturing','Retail','Financial Services','SaaS','Logistics','Hospitality','BPO and Call Centers','Professional Services','Public Sector'].map((industry) => ({
  slug: `industry-${industry.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  label: industry,
  title: `AI Training Tools for ${industry} Teams`,
  meta: `Explore AI training tools used by ${industry} organizations for onboarding, compliance, and upskilling workflows.`,
  intro: `${industry} teams face specific training pressure around speed, consistency, and compliance. These tools are relevant for that operating context.`
}));

export const comparisonPages = [
  { slug: 'synthesia-alternatives', title: 'Synthesia Alternatives for Corporate Training', meta: 'Compare alternatives to Synthesia for AI video training production in L&D contexts.', intro: 'If Synthesia is on your shortlist, compare adjacent tools based on workflow fit, editing control, and localization needs.' },
  { slug: 'descript-vs-camtasia-for-training-videos', title: 'Descript vs Camtasia for Training Videos', meta: 'Head-to-head comparison of Descript and Camtasia for internal training production teams.', intro: 'Both tools support training video production, but they differ in editing model, collaboration, and speed to publish.' },
  { slug: 'chatgpt-vs-claude-for-ld-content', title: 'ChatGPT vs Claude for L&D Content Creation', meta: 'Compare ChatGPT and Claude for SOP rewriting, learning copy, and training knowledge workflows.', intro: 'L&D teams often test both assistants. This page helps frame where each can fit in a training content stack.' },
  { slug: 'murf-vs-elevenlabs-for-training-voiceovers', title: 'Murf vs ElevenLabs for Training Voiceovers', meta: 'Compare Murf and ElevenLabs for internal training voiceover quality, speed, and localization.', intro: 'Voice generation is now table stakes for learning teams. The key difference is workflow and production reliability.' },
  { slug: 'otter-vs-fireflies-for-meeting-knowledge', title: 'Otter vs Fireflies for Meeting Knowledge Capture', meta: 'Compare Otter and Fireflies for training ops note capture, action tracking, and searchable call knowledge.', intro: 'Training ops teams can repurpose meeting insights into enablement assets. This comparison focuses on that use case.' },
  { slug: 'gamma-vs-tome-for-training-presentations', title: 'Gamma vs Tome for Training Presentations', meta: 'Evaluate Gamma and Tome for building training decks and storytelling-based learning presentations.', intro: 'Presentation tools can accelerate workshop prep. This guide compares two AI-native options for learning teams.' },
  { slug: 'notion-ai-vs-confluence-for-training-knowledge', title: 'Notion AI vs Confluence for Training Knowledge Hubs', meta: 'Choose between Notion AI and Confluence for documenting and scaling internal training knowledge.', intro: 'Knowledge systems are a backbone for L&D. This comparison helps decide based on team structure and speed needs.' },
  { slug: 'trainual-vs-knowledge-base-workflows', title: 'Trainual vs General Knowledge Base Workflows', meta: 'Compare Trainual against lighter knowledge-base-based training systems for small teams.', intro: 'Some teams need formal training software, others need practical workflows. This page maps the trade-offs clearly.' },
  { slug: 'heygen-vs-synthesia-for-training-videos', title: 'HeyGen vs Synthesia for Training Videos', meta: 'Compare HeyGen and Synthesia for L&D video production, localization, and enterprise rollout workflows.', intro: 'Both platforms are strong for AI training videos. This comparison helps teams decide based on operating model, QA burden, and rollout speed.' },
  { slug: 'ai-dubbing-vs-subtitles-for-compliance-training', title: 'AI Dubbing vs Subtitles for Compliance Training', meta: 'Decide between AI dubbing and subtitle-first localization for compliance training updates across multilingual teams.', intro: 'Compliance teams often need fast multilingual rollouts. This page helps choose the localization approach that balances risk, speed, and learner comprehension.' },
  { slug: 'scorm-authoring-vs-lms-native-builders', title: 'SCORM Authoring Tools vs LMS Native Builders', meta: 'Evaluate dedicated SCORM authoring tools against LMS-native course builders for implementation speed, governance, and long-term maintainability.', intro: 'Training teams deciding between standalone SCORM authoring and LMS-native builders need more than feature lists. This route frames the decision around rollout risk, update velocity, and operational ownership.' },
  { slug: 'ai-roleplay-simulators-vs-video-only-onboarding', title: 'AI Roleplay Simulators vs Video-Only Onboarding', meta: 'Compare AI roleplay simulators against video-only onboarding for practice depth, manager coaching signal, and ramp-time outcomes.', intro: 'Teams often default to video for onboarding because it is easy to produce. This comparison helps decide when interactive AI roleplay is worth the added operational complexity.' }
];

export const solutionPages = [...useCases.map((i)=>({...i,type:'use-case'})), ...roles.map((i)=>({...i,type:'role'})), ...industries.map((i)=>({...i,type:'industry'}))];
export const getSolutionBySlug = (slug) => solutionPages.find((p) => p.slug === slug);
export const getComparisonBySlug = (slug) => comparisonPages.find((p) => p.slug === slug);
export function pickTools(seed = 0, count = 6) {
  return allListings.slice(seed, seed + count).length === count ? allListings.slice(seed, seed + count) : [...allListings.slice(seed), ...allListings.slice(0, Math.max(0, count - (allListings.length - seed)))];
}
